### ISSUE TITLE
good job, do you have swift-for-javascript-devs  or swift-for-typescript-devs ?

### ISSUE THREAD

**Issue by ghost** [unixzii/swiftui-for-react-devs#1]
thank you very much

**Comment by unixzii** [comment]
By far, no.

Actually, there are so many differences between Swift and JavaScript (or TypeScript), I can rarely list them completely in one page. Maybe taking a look at the [Swift Book](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html) is a better choice.
